run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - path: internal/delivery/graphql/generated.go
      linters:
        - all
    - path: internal/delivery/graphql/model/models_gen.go
      linters:
        - all
