// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Token string `json:"token"`
}

type CreateOrderInput struct {
	Items []*CreateOrderItemInput `json:"items"`
}

type CreateOrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int32  `json:"quantity"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Order struct {
	ID        string       `json:"id"`
	User      *User        `json:"user"`
	Items     []*OrderItem `json:"items"`
	Total     float64      `json:"total"`
	Status    OrderStatus  `json:"status"`
	CreatedAt string       `json:"createdAt"`
}

type OrderConnection struct {
	Items      []*Order `json:"items"`
	TotalCount int32    `json:"totalCount"`
	Page       int32    `json:"page"`
	PageSize   int32    `json:"pageSize"`
}

type OrderItem struct {
	Product   *Product `json:"product"`
	Quantity  int32    `json:"quantity"`
	UnitPrice float64  `json:"unitPrice"`
}

type Product struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Stock int32   `json:"stock"`
}

type ProductConnection struct {
	Items      []*Product `json:"items"`
	TotalCount int32      `json:"totalCount"`
	Page       int32      `json:"page"`
	PageSize   int32      `json:"pageSize"`
}

type ProductFilter struct {
	Name     *string  `json:"name,omitempty"`
	MinPrice *float64 `json:"minPrice,omitempty"`
	MaxPrice *float64 `json:"maxPrice,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "PENDING"
	OrderStatusConfirmed OrderStatus = "CONFIRMED"
	OrderStatusCancelled OrderStatus = "CANCELLED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusConfirmed,
	OrderStatusCancelled,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusConfirmed, OrderStatusCancelled:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
